
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ai.ifontlabs.com
  resources:
  - modelaccuracies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.ifontlabs.com
  resources:
  - modelaccuracies/status
  verbs:
  - get
  - patch
  - update
